create table if not exists genre (id serial primary key,genre_name varchar (40) not null);
create table if not exists artists (id serial primary key,artist_name varchar (50) not null);
create table if not exists genre_lists (artist_id integer references artists(id),genre_id integer references genre(id),constraint pk primary key (artist_id, genre_id));
create table if not exists albums(id serial primary key, album_name varchar (70) not null, album_year integer not null);
create table if not exists albums_lists(albums_id integer references albums(id),artist_id integer references artists(id),constraint pk1 primary key (albums_id, artist_id));
create table if not exists tracks(id serial primary key, timing numeric not null, albums_id integer references albums(id),track_name varchar(100));
create table if not exists tracks_coll(id serial primary key, collection_name varchar(50),coll_year integer);
create table if not exists coll_list(coll_id integer references tracks_coll(id),track_id integer references tracks(id),constraint pk2 primary key (coll_id, track_id));
ALTER TABLE genre ADD UNIQUE (genre_name);
ALTER TABLE albums ADD UNIQUE (album_name);
ALTER TABLE artists ADD UNIQUE (artist_name);
ALTER TABLE tracks_coll ADD UNIQUE (collection_name);